CREATE TABLE IF NOT EXISTS n_users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  login VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  password VARCHAR(64) NOT NULL,
  is_admin TINYINT(1) NOT NULL DEFAULT 0,
  available_ngdu_id INT NULL,
  is_geolog TINYINT(1) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS n_well_matrix (
  id INT AUTO_INCREMENT PRIMARY KEY,
  well VARCHAR(32) NOT NULL,
  oil_field VARCHAR(32) NOT NULL DEFAULT 'BSK',
  nagn TINYINT(1) NOT NULL DEFAULT 0,
  tr_fluid DECIMAL(10,2) DEFAULT 0,
  tr_oil DECIMAL(10,2) DEFAULT 0,
  zamer DECIMAL(10,2) DEFAULT 0,
  zamer_oil DECIMAL(10,2) DEFAULT 0,
  status VARCHAR(64) DEFAULT NULL,
  type TINYINT(1) DEFAULT 1,
  agzu VARCHAR(32) DEFAULT NULL,
  gas DECIMAL(10,2) DEFAULT 0,
  water_tm DECIMAL(10,2) DEFAULT 0,
  update_date DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS well_data (
  id INT AUTO_INCREMENT PRIMARY KEY,
  well VARCHAR(32) NOT NULL UNIQUE,
  coordinates_x VARCHAR(32) DEFAULT NULL,
  coordinates_y VARCHAR(32) DEFAULT NULL,
  c_voltage DECIMAL(10,2) DEFAULT 0,
  c_power DECIMAL(10,2) DEFAULT 0,
  c_freq DECIMAL(10,2) DEFAULT 0,
  c_current DECIMAL(10,2) DEFAULT 0,
  c_current_min DECIMAL(10,2) DEFAULT 0,
  c_current_max DECIMAL(10,2) DEFAULT 0,
  c_speed DECIMAL(10,2) DEFAULT 0,
  c_temp DECIMAL(10,2) DEFAULT 0,
  c_type VARCHAR(64) DEFAULT NULL,
  c_last_update DATETIME DEFAULT CURRENT_TIMESTAMP,
  working TINYINT(1) DEFAULT 1,
  type TINYINT(1) DEFAULT 1
);

CREATE TABLE IF NOT EXISTS n_2hour (
  id INT AUTO_INCREMENT PRIMARY KEY,
  oil_field VARCHAR(32) NOT NULL DEFAULT 'BSK',
  current_debit DECIMAL(12,2) DEFAULT 0,
  tech_rezh DECIMAL(12,2) DEFAULT 0,
  debit_last_day DECIMAL(12,2) DEFAULT 0,
  current_debit_nak DECIMAL(12,2) DEFAULT 0,
  tech_rezh_nak DECIMAL(12,2) DEFAULT 0,
  debit_last_day_nak DECIMAL(12,2) DEFAULT 0,
  n_current_debit DECIMAL(12,2) DEFAULT 0,
  n_tech_rezh DECIMAL(12,2) DEFAULT 0,
  n_debit_last_day DECIMAL(12,2) DEFAULT 0,
  n_current_debit_nak DECIMAL(12,2) DEFAULT 0,
  n_tech_rezh_nak DECIMAL(12,2) DEFAULT 0,
  n_debit_last_day_nak DECIMAL(12,2) DEFAULT 0,
  wat_out DECIMAL(12,2) DEFAULT 0,
  time VARCHAR(8) NOT NULL,
  Tin TINYINT(1) DEFAULT 1
);

CREATE TABLE IF NOT EXISTS n_2hour_arch (
  id INT AUTO_INCREMENT PRIMARY KEY,
  oil_field VARCHAR(32) NOT NULL DEFAULT 'BSK',
  date DATE NOT NULL,
  time VARCHAR(8) NOT NULL,
  current_debit DECIMAL(12,2) DEFAULT 0,
  tech_rezh DECIMAL(12,2) DEFAULT 0,
  debit_last_day DECIMAL(12,2) DEFAULT 0,
  current_debit_nak DECIMAL(12,2) DEFAULT 0,
  tech_rezh_nak DECIMAL(12,2) DEFAULT 0,
  debit_last_day_nak DECIMAL(12,2) DEFAULT 0,
  n_current_debit DECIMAL(12,2) DEFAULT 0,
  n_tech_rezh DECIMAL(12,2) DEFAULT 0,
  n_debit_last_day DECIMAL(12,2) DEFAULT 0,
  n_current_debit_nak DECIMAL(12,2) DEFAULT 0,
  n_tech_rezh_nak DECIMAL(12,2) DEFAULT 0,
  n_debit_last_day_nak DECIMAL(12,2) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS n_last10 (
  id INT AUTO_INCREMENT PRIMARY KEY,
  well VARCHAR(32) NOT NULL,
  start_date DATE DEFAULT NULL,
  end_date DATE DEFAULT NULL,
  work VARCHAR(128) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS n_lenta (
  id INT AUTO_INCREMENT PRIMARY KEY,
  criticality VARCHAR(32) DEFAULT NULL,
  extraction VARCHAR(64) DEFAULT NULL,
  event VARCHAR(255) DEFAULT NULL,
  status VARCHAR(32) DEFAULT 'open',
  oil_field VARCHAR(32) DEFAULT 'BSK',
  agzu VARCHAR(64) DEFAULT NULL,
  well VARCHAR(32) DEFAULT NULL,
  otvod VARCHAR(64) DEFAULT NULL,
  opened DATETIME DEFAULT CURRENT_TIMESTAMP,
  closed DATETIME DEFAULT NULL,
  user_name VARCHAR(128) DEFAULT NULL,
  user_email VARCHAR(128) DEFAULT NULL,
  delta DECIMAL(12,2) DEFAULT 0,
  comment TEXT NULL
);

CREATE TABLE IF NOT EXISTS n_wincctags (
  id INT AUTO_INCREMENT PRIMARY KEY,
  oil_field VARCHAR(32) DEFAULT 'BSK',
  description VARCHAR(255) DEFAULT NULL,
  tag_key VARCHAR(128) NOT NULL,
  tag_value VARCHAR(128) DEFAULT NULL,
  vlog_arch DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS abc_data (
  id INT AUTO_INCREMENT PRIMARY KEY,
  well VARCHAR(32) NOT NULL,
  date DATE NOT NULL,
  tm_fluid DECIMAL(12,2) DEFAULT 0,
  tm_oil DECIMAL(12,2) DEFAULT 0,
  tm_water DECIMAL(12,2) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS chrp_archive (
  id INT AUTO_INCREMENT PRIMARY KEY,
  well_name VARCHAR(32) NOT NULL,
  date_time DATETIME NOT NULL,
  c_voltage DECIMAL(10,2) DEFAULT 0,
  c_power DECIMAL(10,2) DEFAULT 0,
  c_freq DECIMAL(10,2) DEFAULT 0,
  c_current DECIMAL(10,2) DEFAULT 0,
  c_speed DECIMAL(10,2) DEFAULT 0,
  c_temp DECIMAL(10,2) DEFAULT 0
);

CREATE TABLE IF NOT EXISTS oil_loss (
  id INT AUTO_INCREMENT PRIMARY KEY,
  oil_field VARCHAR(32) NOT NULL DEFAULT 'BSK',
  well VARCHAR(32) NOT NULL,
  date DATE NOT NULL,
  tm_oil DECIMAL(12,2) DEFAULT 0,
  well_work_time DECIMAL(12,2) DEFAULT 0,
  tm_obv DECIMAL(12,2) DEFAULT 0,
  tm_fluid DECIMAL(12,2) DEFAULT 0,
  water_lab DECIMAL(12,2) DEFAULT 0
);
